"""Coastal Mozambique districts monitored for AA storm wind exposure.

Historically mirrored ``alerting`` TypeScript; list kept here for the Python AA worker.
"""

# ruff: noqa: RUF001
ALL_DISTRICTS_IN_COASTAL_PROVINCE: tuple[str, ...] = (
    "Ancuabe",
    "Balama",
    "Chiure",
    "Cidade De Pemba",
    "Ibo",
    "Macomia",
    "Mecufi",
    "Meluco",
    "Metuge",
    "Mocimboa Da Praia",
    "Montepuez",
    "Mueda",
    "Muidumbe",
    "Namuno",
    "Nangade",
    "Palma",
    "Quissanga",
    "Angoche",
    "Cidade De Nampula",
    "Erati",
    "Ilha De Moçambique",
    "Lalaua",
    "Larde",
    "Liúpo",
    "Malema",
    "Meconta",
    "Mecuburi",
    "Memba",
    "Mogincual",
    "Mogovolas",
    "Moma",
    "Monapo",
    "Mossuril",
    "Muecate",
    "Murrupula",
    "Nacala",
    "Nacala-A-Velha",
    "Nacaroa",
    "Nampula",
    "Rapale",
    "Ribaue",
    "Alto Molocue",
    "Chinde",
    "Derre",
    "Gile",
    "Gurue",
    "Ile",
    "Inhassunge",
    "Luabo",
    "Lugela",
    "Maganja Da Costa",
    "Milange",
    "Mocuba",
    "Mocubela",
    "Molumbo",
    "Mopeia",
    "Morrumbala",
    "Mulevala",
    "Namacurra",
    "Namarroi",
    "Nicoadala",
    "Pebane",
    "Quelimane",
    "Buzi",
    "Caia",
    "Chemba",
    "Cheringoma",
    "Chibabava",
    "Cidade Da Beira",
    "Dondo",
    "Gorongosa",
    "Machanga",
    "Maringue",
    "Marromeu",
    "Muanza",
    "Nhamatanda",
    "Cidade De Inhambane",
    "Funhalouro",
    "Govuro",
    "Homoine",
    "Inharrime",
    "Inhassoro",
    "Jangamo",
    "Mabote",
    "Massinga",
    "Maxixe",
    "Morrumbene",
    "Panda",
    "Vilankulo",
    "Zavala",
    "Bilene",
    "Chibuto",
    "Chicualacuala",
    "Chigubo",
    "Chokwe",
    "Chongoene",
    "Cidade De Xai-Xai",
    "Guija",
    "Limpopo",
    "Mabalane",
    "Mandlakaze",
    "Mapai",
    "Massangena",
    "Massingir",
    "Boane",
    "Cidade Da Matola",
    "Magude",
    "Manhiça",
    "Marracuene",
    "Matutuine",
    "Moamba",
    "Namaacha",
    "Cidade De Maputo",
)
