import { AnticipatoryActionState } from 'context/anticipatoryAction/AADroughtStateSlice/types';

export const defaultDialogs = [
  {
    text: 'How to read this screen',
    onclick: () => {},
  },
];

export const mockAAInput = [
  // This is here to set window size.
  {
    district: 'Caia',
    index: 'SPI DJF',
    category: 'Moderate',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-11-01',
    date_set: '2023-12-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.17',
    prob_set: '0.18',
    trigger_ready: '0.22',
    trigger_set: '0.0',
    state: 'na',
    new_tag: '0',
  },

  // Mild, ready not valid, set not valid, 08-09
  {
    district: 'Changara',
    index: 'SPI DJF',
    category: 'Mild',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-08-01',
    date_set: '2023-09-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.16',
    prob_set: '0.12',
    trigger_ready: '0.17',
    trigger_set: '0.30',
    state: 'na',
    new_tag: '0',
  },
  // Mild, ready not valid, set valid, 09-10
  {
    district: 'Changara',
    index: 'SPI DJF',
    category: 'Mild',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-09-01',
    date_set: '2023-10-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.22',
    prob_set: '0.34',
    trigger_ready: '0.30',
    trigger_set: '0.33',
    state: 'na',
    new_tag: '0',
  },
  // Moderate, ready valid, set not valid, 09-10
  {
    district: 'Changara',
    index: 'SPI DJF',
    category: 'Moderate',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-09-01',
    date_set: '2023-10-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.19',
    prob_set: '0.25',
    trigger_ready: '0.10',
    trigger_set: '0.26',
    state: 'na',
    new_tag: '0',
  },
  // Mild, ready valid, set valid, 10-11
  {
    district: 'Changara',
    index: 'SPI DJF',
    category: 'Mild',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-10-01',
    date_set: '2023-11-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.31',
    prob_set: '0.28',
    trigger_ready: '0.20',
    trigger_set: '0.25',
    state: 'na',
    new_tag: '0',
  },
  // Moderate, ready valid, set not valid, 10-11
  {
    district: 'Changara',
    index: 'SPI DJF',
    category: 'Moderate',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-10-01',
    date_set: '2023-11-01',
    issue_ready: '9.0',
    issue_set: '10.0',
    prob_ready: '0.28',
    prob_set: '0.22',
    trigger_ready: '0.20',
    trigger_set: '0.30',
    state: 'na',
    new_tag: '0',
  },
];

export const mockAAData: AnticipatoryActionState['data'] = {
  'Window 1': {
    Caia: [
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.17,
        trigger: 0.22,
        date: '2023-11-01',
        season: '2023-24',
        isValid: false,
        isOtherPhaseValid: false,
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.18,
        trigger: 0,
        date: '2023-12-01',
        season: '2023-24',
        isValid: false,
        isOtherPhaseValid: false,
      },
    ],
    Changara: [
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.16,
        trigger: 0.17,
        date: '2023-08-01',
        season: '2023-24',
        isValid: false,
        isOtherPhaseValid: false,
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.22,
        trigger: 0.3,
        date: '2023-09-01',
        season: '2023-24',
        isValid: false,
        isOtherPhaseValid: false,
      },
      {
        category: 'Moderate',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: true,
        phase: 'Ready',
        probability: 0.19,
        trigger: 0.1,
        date: '2023-09-01',
        season: '2023-24',
        isValid: true,
        isOtherPhaseValid: false,
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.12,
        trigger: 0.3,
        date: '2023-09-01',
        season: '2023-24',
        isValid: false,
        isOtherPhaseValid: false,
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.31,
        trigger: 0.2,
        date: '2023-10-01',
        season: '2023-24',
        isValid: true,
        isOtherPhaseValid: true,
      },
      {
        category: 'Moderate',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.28,
        trigger: 0.2,
        date: '2023-10-01',
        season: '2023-24',
        isValid: true,
        isOtherPhaseValid: false,
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.34,
        trigger: 0.33,
        date: '2023-10-01',
        season: '2023-24',
        isValid: false,
        isOtherPhaseValid: false,
      },
      {
        category: 'Moderate',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.25,
        trigger: 0.26,
        date: '2023-10-01',
        season: '2023-24',
        isValid: false,
        isOtherPhaseValid: true,
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: true,
        phase: 'Set',
        probability: 0.28,
        trigger: 0.25,
        date: '2023-11-01',
        season: '2023-24',
        isValid: true,
        isOtherPhaseValid: true,
      },
      {
        category: 'Moderate',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.22,
        trigger: 0.3,
        date: '2023-11-01',
        season: '2023-24',
        isValid: false,
        isOtherPhaseValid: true,
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.28,
        trigger: 0.25,
        date: '2023-12-01',
        season: '2023-24',
        isValid: true,
        computedRow: true,
        isOtherPhaseValid: true,
      },
    ],
  },
  'Window 2': {
    Caia: [],
    Changara: [],
  },
};

export const mockAARenderedDistricts: AnticipatoryActionState['renderedDistricts'] =
  {
    'Window 1': {
      Caia: [
        {
          category: 'ny',
          phase: 'ny',
          isNew: false,
        },
      ],
      Changara: [
        {
          category: 'Moderate',
          phase: 'Ready',
          isNew: false,
        },
        {
          category: 'Mild',
          phase: 'Ready',
          isNew: false,
        },
      ],
    },
    'Window 2': {
      Caia: [
        {
          category: 'ny',
          phase: 'ny',
          isNew: false,
        },
      ],
      Changara: [
        {
          category: 'ny',
          phase: 'ny',
          isNew: false,
        },
      ],
    },
  };
