version: 2.1
jobs:
  build_frontend:
    docker:
      - image: circleci/node:12.9.1-browsers
  
    working_directory: ~/repo

    steps:
        - checkout

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
        
        - run: cd web && yarn install
    
        - save_cache:
            paths:
            - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
        
        - run: cd web && yarn test
        - run: cd web && yarn lint
        - run: cd web && yarn build

  build_api:
    machine:
      image: ubuntu-1604:201903-01 
    steps:
        - checkout

        - run:
            name: Install Docker Compose
            command: |
                curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                chmod +x ~/docker-compose
                sudo mv ~/docker-compose /usr/local/bin/docker-compose

        - run:
            name: Build containers
            command: cd api-flask && docker-compose build api
        - run:
            name: Run linters
            command: cd api-flask && make api-lint
        - run:
            name: Run tests
            command: cd api-flask && make api-test

workflows:
  version: 2.1
  build:
      jobs:
          - build_frontend
          - build_api
