export type WMS_OUTPUT_FORMAT =
  | "image/png"
  | "image/png8"
  | "image/jpeg"
  | "image/vnd.jpeg-png"
  | "image/vnd.jpeg-png8"
  | "image/gif"
  | "image/tiff"
  | "image/tiff8"
  | "image/geotiff"
  | "image/geotiff8"
  | "image/svg"
  | "application/pdf"
  | "rss"
  | "kml"
  | "kmz"
  | "application/openlayers"
  | "application/json;type=utfgrid";
