import { calculateMapRenderedDistricts, transform } from '.';

describe('Anticipatory Action', () => {
  test('Transforms input', () => {
    const out = transform(mockInput);
    const data = Object.fromEntries(
      out.windowData.map(x => [x.windowKey, x.data]),
    );
    expect(data).toEqual(expectedOutput);
  });

  test('Calculate rendered districts', () => {
    const filters: any = {
      selectedDate: '2023-10-01',
      selectedWindow: 'Window 1',
      categories: {
        Severe: true,
        Moderate: true,
        Mild: true,
        na: true,
        ny: true,
      },
    };
    const out = calculateMapRenderedDistricts({
      data: expectedOutput as any,
      filters,
    });

    expect(out).toEqual(expectedRenderedDistricts);
  });
});

const mockInput = [
  {
    district: '',
  },
  {
    district: 'Caia',
    index: 'DRY DJ',
    category: 'Mild',
    window: 'Window 1',
    season: '2023-24',
    type: 'DRYSPELL',
    date_ready: '2023-09-01',
    date_set: '2023-10-01',
    issue_ready: '9.0',
    issue_set: '10.0',
    prob_ready: '0.27',
    prob_set: '0.23',
    trigger_ready: '0.24',
    trigger_set: '0.22',
    state: 'set',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Caia',
    index: 'DRY DJ',
    category: 'Moderate',
    window: 'Window 1',
    season: '2023-24',
    type: 'DRYSPELL',
    date_ready: '2023-08-01',
    date_set: '2023-09-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.21',
    prob_set: '0.26',
    trigger_ready: '0.1',
    trigger_set: '0.25',
    state: 'set',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Caia',
    index: 'DRY DJ',
    category: 'Severe',
    window: 'Window 1',
    season: '2023-24',
    type: 'DRYSPELL',
    date_ready: '2023-08-01',
    date_set: '2023-09-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.14',
    prob_set: '0.21',
    trigger_ready: '0.1',
    trigger_set: '0.22',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Caia',
    index: 'DRY DJ',
    category: 'Severe',
    window: 'Window 1',
    season: '2023-24',
    type: 'DRYSPELL',
    date_ready: '2023-09-01',
    date_set: '2023-10-01',
    issue_ready: '9.0',
    issue_set: '10.0',
    prob_ready: '0.21',
    prob_set: '0.12',
    trigger_ready: '0.24',
    trigger_set: '0.19',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Caia',
    index: 'DRY FM',
    category: 'Mild',
    window: 'Window 2',
    season: '2023-24',
    type: 'DRYSPELL',
    date_ready: '2023-10-01',
    date_set: '2023-11-01',
    issue_ready: '10.0',
    issue_set: '11.0',
    prob_ready: '0.24',
    prob_set: '0.35',
    trigger_ready: '0.27',
    trigger_set: '0.16',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Caia',
    index: 'SPI DJF',
    category: 'Mild',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-08-01',
    date_set: '2023-09-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.2',
    prob_set: '0.23',
    trigger_ready: '0.27',
    trigger_set: '0.0',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Caia',
    index: 'SPI DJF',
    category: 'Moderate',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-08-01',
    date_set: '2023-09-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.17',
    prob_set: '0.18',
    trigger_ready: '0.22',
    trigger_set: '0.0',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Caia',
    index: 'SPI MA',
    category: 'Moderate',
    window: 'Window 2',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-10-01',
    date_set: '2023-11-01',
    issue_ready: '10.0',
    issue_set: '11.0',
    prob_ready: '0.11',
    prob_set: '0.16',
    trigger_ready: '0.0',
    trigger_set: '0.25',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Caia',
    index: 'SPI MA',
    category: 'Moderate',
    window: 'Window 2',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-11-01',
    date_set: '2023-12-01',
    issue_ready: '11.0',
    issue_set: '12.0',
    prob_ready: '0.16',
    prob_set: '0.49',
    trigger_ready: '0.25',
    trigger_set: '0.0',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Caia',
    index: 'SPI MA',
    category: 'Severe',
    window: 'Window 2',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-10-01',
    date_set: '2023-11-01',
    issue_ready: '10.0',
    issue_set: '11.0',
    prob_ready: '0.09',
    prob_set: '0.12',
    trigger_ready: '0.0',
    trigger_set: '0.24',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Caia',
    index: 'SPI MA',
    category: 'Severe',
    window: 'Window 2',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-11-01',
    date_set: '2023-12-01',
    issue_ready: '11.0',
    issue_set: '12.0',
    prob_ready: '0.12',
    prob_set: '0.41',
    trigger_ready: '0.24',
    trigger_set: '0.0',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Caia',
    index: 'SPI MAM',
    category: 'Mild',
    window: 'Window 2',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-11-01',
    date_set: '2023-12-01',
    issue_ready: '11.0',
    issue_set: '12.0',
    prob_ready: '0.2',
    prob_set: '0.5',
    trigger_ready: '0.3',
    trigger_set: '0.0',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Changara',
    index: 'DRY DJ',
    category: 'Mild',
    window: 'Window 1',
    season: '2023-24',
    type: 'DRYSPELL',
    date_ready: '2023-08-01',
    date_set: '2023-09-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.16',
    prob_set: '0.12',
    trigger_ready: '0.16',
    trigger_set: '0.3',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Changara',
    index: 'DRY MA',
    category: 'Moderate',
    window: 'Window 2',
    season: '2023-24',
    type: 'DRYSPELL',
    date_ready: '2023-12-01',
    date_set: '2024-01-01',
    issue_ready: '12.0',
    issue_set: '1.0',
    prob_ready: '0.24',
    prob_set: '0.29',
    trigger_ready: '0.32',
    trigger_set: '0.16',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Changara',
    index: 'DRY MA',
    category: 'Severe',
    window: 'Window 2',
    season: '2023-24',
    type: 'DRYSPELL',
    date_ready: '2023-11-01',
    date_set: '2023-12-01',
    issue_ready: '11.0',
    issue_set: '12.0',
    prob_ready: '0.06',
    prob_set: '0.21',
    trigger_ready: '0.0',
    trigger_set: '0.28',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Changara',
    index: 'DRY MA',
    category: 'Severe',
    window: 'Window 2',
    season: '2023-24',
    type: 'DRYSPELL',
    date_ready: '2023-12-01',
    date_set: '2024-01-01',
    issue_ready: '12.0',
    issue_set: '1.0',
    prob_ready: '0.21',
    prob_set: '0.23',
    trigger_ready: '0.28',
    trigger_set: '0.0',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Changara',
    index: 'SPI DJF',
    category: 'Moderate',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-08-01',
    date_set: '2023-09-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.22',
    prob_set: '0.28',
    trigger_ready: '0.0',
    trigger_set: '0.33',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Changara',
    index: 'SPI DJF',
    category: 'Moderate',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-09-01',
    date_set: '2023-10-01',
    issue_ready: '9.0',
    issue_set: '10.0',
    prob_ready: '0.28',
    prob_set: '0.22',
    trigger_ready: '0.33',
    trigger_set: '0.0',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Changara',
    index: 'SPI DJF',
    category: 'Severe',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-08-01',
    date_set: '2023-09-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.19',
    prob_set: '0.25',
    trigger_ready: '0.0',
    trigger_set: '0.26',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Changara',
    index: 'SPI DJF',
    category: 'Severe',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-09-01',
    date_set: '2023-10-01',
    issue_ready: '9.0',
    issue_set: '10.0',
    prob_ready: '0.25',
    prob_set: '0.17',
    trigger_ready: '0.26',
    trigger_set: '0.0',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Changara',
    index: 'SPI MAM',
    category: 'Mild',
    window: 'Window 2',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-11-01',
    date_set: '2023-12-01',
    issue_ready: '11.0',
    issue_set: '12.0',
    prob_ready: '0.41',
    prob_set: '0.41',
    trigger_ready: '0.21',
    trigger_set: '0.31',
    state: 'set',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Changara',
    index: 'SPI MAM',
    category: 'Mild',
    window: 'Window 2',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-12-01',
    date_set: '2024-01-01',
    issue_ready: '12.0',
    issue_set: '1.0',
    prob_ready: '0.41',
    prob_set: '0.47',
    trigger_ready: '0.31',
    trigger_set: '0.11',
    state: 'set',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: 'Changara',
    index: 'SPI NDJ',
    category: 'Mild',
    window: 'Window 1',
    season: '2023-24',
    type: 'SPI',
    date_ready: '2023-08-01',
    date_set: '2023-09-01',
    issue_ready: '8.0',
    issue_set: '9.0',
    prob_ready: '0.31',
    prob_set: '0.28',
    trigger_ready: '0.0',
    trigger_set: '0.38',
    state: 'na',
    new_tag: '0',
  },
  {
    district: '',
  },
  {
    district: '',
  },
];

const expectedOutput = {
  'Window 1': {
    Caia: [
      {
        category: 'Severe',
        district: 'Caia',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.12,
        trigger: 0.19,
        date: '2023-10-01',
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.23,
        trigger: 0.22,
        date: '2023-10-01',
        computedRow: true,
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.23,
        trigger: 0.22,
        date: '2023-10-01',
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.23,
        trigger: 0.22,
        date: '2023-10-01',
        computedRow: true,
      },
      {
        category: 'Severe',
        district: 'Caia',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.21,
        trigger: 0.22,
        date: '2023-09-01',
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.26,
        trigger: 0.25,
        date: '2023-09-01',
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.18,
        trigger: 0,
        date: '2023-09-01',
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.27,
        trigger: 0.24,
        date: '2023-09-01',
        computedRow: true,
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.23,
        trigger: 0,
        date: '2023-09-01',
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.27,
        trigger: 0.24,
        date: '2023-09-01',
        computedRow: true,
      },
      {
        category: 'Severe',
        district: 'Caia',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.21,
        trigger: 0.24,
        date: '2023-09-01',
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.27,
        trigger: 0.24,
        date: '2023-09-01',
      },
      {
        category: 'Severe',
        district: 'Caia',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.14,
        trigger: 0.1,
        date: '2023-08-01',
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.21,
        trigger: 0.1,
        date: '2023-08-01',
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.17,
        trigger: 0.22,
        date: '2023-08-01',
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.2,
        trigger: 0.27,
        date: '2023-08-01',
      },
    ],
    Changara: [
      {
        category: 'Severe',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.17,
        trigger: 0,
        date: '2023-10-01',
      },
      {
        category: 'Severe',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.22,
        trigger: 0,
        date: '2023-10-01',
        computedRow: true,
      },
      {
        category: 'Moderate',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.22,
        trigger: 0,
        date: '2023-10-01',
      },
      {
        category: 'Moderate',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.22,
        trigger: 0,
        date: '2023-10-01',
        computedRow: true,
      },
      {
        category: 'Severe',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.25,
        trigger: 0.26,
        date: '2023-09-01',
      },
      {
        category: 'Moderate',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.28,
        trigger: 0.33,
        date: '2023-09-01',
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.12,
        trigger: 0.3,
        date: '2023-09-01',
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI NDJ',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Set',
        probability: 0.28,
        trigger: 0.38,
        date: '2023-09-01',
      },
      {
        category: 'Severe',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.25,
        trigger: 0.26,
        date: '2023-09-01',
      },
      {
        category: 'Moderate',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.28,
        trigger: 0.33,
        date: '2023-09-01',
      },
      {
        category: 'Severe',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.19,
        trigger: 0,
        date: '2023-08-01',
      },
      {
        category: 'Moderate',
        district: 'Changara',
        index: 'SPI DJF',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.22,
        trigger: 0,
        date: '2023-08-01',
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'DRY DJ',
        type: 'DRYSPELL',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.16,
        trigger: 0.16,
        date: '2023-08-01',
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI NDJ',
        type: 'SPI',
        window: 'Window 1',
        new: false,
        phase: 'Ready',
        probability: 0.31,
        trigger: 0,
        date: '2023-08-01',
      },
    ],
  },
  'Window 2': {
    Caia: [
      {
        category: 'Severe',
        district: 'Caia',
        index: 'SPI MA',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.41,
        trigger: 0,
        date: '2023-12-01',
      },
      {
        category: 'Severe',
        district: 'Caia',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.5,
        trigger: 0,
        date: '2023-12-01',
        computedRow: true,
      },
      {
        computedRow: true,
        category: 'Severe',
        phase: 'Set',
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'SPI MA',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.49,
        trigger: 0,
        date: '2023-12-01',
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.5,
        trigger: 0,
        date: '2023-12-01',
        computedRow: true,
      },
      {
        computedRow: true,
        category: 'Moderate',
        phase: 'Set',
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.5,
        trigger: 0,
        date: '2023-12-01',
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.5,
        trigger: 0,
        date: '2023-12-01',
        computedRow: true,
      },
      {
        category: 'Severe',
        district: 'Caia',
        index: 'SPI MA',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.12,
        trigger: 0.24,
        date: '2023-11-01',
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'SPI MA',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.16,
        trigger: 0.25,
        date: '2023-11-01',
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'DRY FM',
        type: 'DRYSPELL',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.35,
        trigger: 0.16,
        date: '2023-11-01',
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.2,
        trigger: 0.3,
        date: '2023-11-01',
        computedRow: true,
      },
      {
        computedRow: true,
        category: 'Mild',
        phase: 'Set',
      },
      {
        category: 'Severe',
        district: 'Caia',
        index: 'SPI MA',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Ready',
        probability: 0.12,
        trigger: 0.24,
        date: '2023-11-01',
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'SPI MA',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Ready',
        probability: 0.16,
        trigger: 0.25,
        date: '2023-11-01',
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Ready',
        probability: 0.2,
        trigger: 0.3,
        date: '2023-11-01',
      },
      {
        category: 'Severe',
        district: 'Caia',
        index: 'SPI MA',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Ready',
        probability: 0.09,
        trigger: 0,
        date: '2023-10-01',
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'SPI MA',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Ready',
        probability: 0.11,
        trigger: 0,
        date: '2023-10-01',
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'DRY FM',
        type: 'DRYSPELL',
        window: 'Window 2',
        new: false,
        phase: 'Ready',
        probability: 0.24,
        trigger: 0.27,
        date: '2023-10-01',
      },
    ],
    Changara: [
      {
        category: 'Severe',
        district: 'Changara',
        index: 'DRY MA',
        type: 'DRYSPELL',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.23,
        trigger: 0,
        date: '2024-01-01',
      },
      {
        category: 'Severe',
        district: 'Changara',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.47,
        trigger: 0.11,
        date: '2024-01-01',
        computedRow: true,
      },
      {
        category: 'Moderate',
        district: 'Changara',
        index: 'DRY MA',
        type: 'DRYSPELL',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.29,
        trigger: 0.16,
        date: '2024-01-01',
      },
      {
        category: 'Moderate',
        district: 'Changara',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.47,
        trigger: 0.11,
        date: '2024-01-01',
        computedRow: true,
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.47,
        trigger: 0.11,
        date: '2024-01-01',
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.47,
        trigger: 0.11,
        date: '2024-01-01',
        computedRow: true,
      },
      {
        category: 'Severe',
        district: 'Changara',
        index: 'DRY MA',
        type: 'DRYSPELL',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.21,
        trigger: 0.28,
        date: '2023-12-01',
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.41,
        trigger: 0.31,
        date: '2023-12-01',
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Set',
        probability: 0.41,
        trigger: 0.31,
        date: '2023-12-01',
        computedRow: true,
      },
      {
        category: 'Severe',
        district: 'Changara',
        index: 'DRY MA',
        type: 'DRYSPELL',
        window: 'Window 2',
        new: false,
        phase: 'Ready',
        probability: 0.21,
        trigger: 0.28,
        date: '2023-12-01',
      },
      {
        category: 'Moderate',
        district: 'Changara',
        index: 'DRY MA',
        type: 'DRYSPELL',
        window: 'Window 2',
        new: false,
        phase: 'Ready',
        probability: 0.24,
        trigger: 0.32,
        date: '2023-12-01',
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Ready',
        probability: 0.41,
        trigger: 0.31,
        date: '2023-12-01',
      },
      {
        category: 'Severe',
        district: 'Changara',
        index: 'DRY MA',
        type: 'DRYSPELL',
        window: 'Window 2',
        new: false,
        phase: 'Ready',
        probability: 0.06,
        trigger: 0,
        date: '2023-11-01',
      },
      {
        category: 'Mild',
        district: 'Changara',
        index: 'SPI MAM',
        type: 'SPI',
        window: 'Window 2',
        new: false,
        phase: 'Ready',
        probability: 0.41,
        trigger: 0.21,
        date: '2023-11-01',
      },
    ],
  },
};

const expectedRenderedDistricts = {
  'Window 1': {
    Caia: {
      category: 'Moderate',
      phase: 'Set',
      isNew: false,
    },
    Changara: {
      category: 'Severe',
      phase: 'Set',
      isNew: false,
    },
  },
  'Window 2': {
    Caia: {
      category: 'Severe',
      phase: 'Ready',
      isNew: false,
    },
    Changara: {
      category: 'ny',
      phase: 'ny',
      isNew: false,
    },
  },
};
