// Coastal provinces only: Cabo Delgado, Nampula, Zambezia, Sofala, Inhambane, Gaza, Maputo, Maputo City
export const allDistrictsInCoastalProvince: string[] = [
  // Cabo Delgado
  'Ancuabe',
  'Balama',
  'Chiure',
  'Cidade De Pemba',
  'Ibo',
  'Macomia',
  'Mecufi',
  'Meluco',
  'Metuge',
  'Mocimboa Da Praia',
  'Montepuez',
  'Mueda',
  'Muidumbe',
  'Namuno',
  'Nangade',
  'Palma',
  'Quissanga',
  // Nampula
  'Angoche',
  'Cidade De Nampula',
  'Erati',
  'Ilha De Moçambique',
  'Lalaua',
  'Larde',
  'Liúpo',
  'Malema',
  'Meconta',
  'Mecuburi',
  'Memba',
  'Mogincual',
  'Mogovolas',
  'Moma',
  'Monapo',
  'Mossuril',
  'Muecate',
  'Murrupula',
  'Nacala',
  'Nacala-A-Velha',
  'Nacaroa',
  'Nampula',
  'Rapale',
  'Ribaue',
  // Zambezia
  'Alto Molocue',
  'Chinde',
  'Derre',
  'Gile',
  'Gurue',
  'Ile',
  'Inhassunge',
  'Luabo',
  'Lugela',
  'Maganja Da Costa',
  'Milange',
  'Mocuba',
  'Mocubela',
  'Molumbo',
  'Mopeia',
  'Morrumbala',
  'Mulevala',
  'Namacurra',
  'Namarroi',
  'Nicoadala',
  'Pebane',
  'Quelimane',
  // Sofala
  'Buzi',
  'Caia',
  'Chemba',
  'Cheringoma',
  'Chibabava',
  'Cidade Da Beira',
  'Dondo',
  'Gorongosa',
  'Machanga',
  'Maringue',
  'Marromeu',
  'Muanza',
  'Nhamatanda',
  // Inhambane
  'Cidade De Inhambane',
  'Funhalouro',
  'Govuro',
  'Homoine',
  'Inharrime',
  'Inhassoro',
  'Jangamo',
  'Mabote',
  'Massinga',
  'Maxixe',
  'Morrumbene',
  'Panda',
  'Vilankulo',
  'Zavala',
  // Gaza
  'Bilene',
  'Chibuto',
  'Chicualacuala',
  'Chigubo',
  'Chokwe',
  'Chongoene',
  'Cidade De Xai-Xai',
  'Guija',
  'Limpopo',
  'Mabalane',
  'Mandlakaze',
  'Mapai',
  'Massangena',
  'Massingir',
  // Maputo
  'Boane',
  'Cidade Da Matola',
  'Magude',
  'Manhiça',
  'Marracuene',
  'Matutuine',
  'Moamba',
  'Namaacha',
  // Maputo City
  'Cidade De Maputo',
];
