import { AnticipatoryActionState } from 'context/anticipatoryActionStateSlice/types';

export const mockAAData: AnticipatoryActionState['data'] = {
  'Window 1': {},
  'Window 2': {
    Caia: [
      {
        category: 'Severe',
        district: 'Caia',
        index: 'SPI MA',
        phase: 'Set',
        probability: 0.41,
        trigger: 0,
        type: 'SPI',
        window: 'Window 2',
        date: '2023-12-01',
        new: false,
      },
      {
        category: 'Moderate',
        district: 'Caia',
        index: 'SPI MA',
        phase: 'Set',
        probability: 0.49,
        trigger: 0,
        type: 'SPI',
        window: 'Window 2',
        date: '2023-12-01',
        new: false,
      },
      {
        category: 'Mild',
        district: 'Caia',
        index: 'SPI MAM',
        phase: 'Set',
        probability: 0.5,
        trigger: 0,
        type: 'SPI',
        window: 'Window 2',
        date: '2023-12-01',
        new: false,
      },
      {
        category: 'Severe',
        district: 'Caia',
        index: 'SPI MA',
        phase: 'Ready',
        probability: 0.12,
        trigger: 0.24,
        type: 'SPI',
        window: 'Window 2',
        date: '2023-11-01',
        new: false,
      },
      {
        category: 'Severe',
        district: 'Caia',
        index: 'SPI MA',
        phase: 'Set',
        probability: 0.12,
        trigger: 0.24,
        type: 'SPI',
        window: 'Window 2',
        date: '2023-11-01',
        new: false,
      },
    ],
  },
};
