[tool.pip-audit]
# Exit with error code 1 if vulnerabilities are found
exit-code = 1

# Show full vulnerability report
format = "text"

# Do not include development dependencies in audit
dev = false

# Show progress bar
progress = true

# Mark specific vulnerabilities as safe/ignored
[tool.pip-audit.vulnerabilities]
GHSA-pq67-6m6q-mj2v = "ignored"
