name: PRISM Test

on:
  # Run on all pull requests and on pushes to main.
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      ORG_LEVEL_TOKEN: ${{secrets.ORG_LEVEL_TOKEN}}
    strategy:
      matrix:
        python-version: ["3.10", 3.9, 3.8, 3.7]
      # run the matrix jobs one after the other so they can benefit from caching
      max-parallel: 1

    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          # Version of Poetry to use
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Check formatting with black and isort
        run: |
          poetry run black --check .
          poetry run isort --check .
